"""P3.3 -- Result 56's capped block against the taper on the live BOPTEST heat pump. PRE-REGISTERED.

This docstring is the pre-registration. It was committed before any scored episode ran, and the
routine below runs exactly what it states at its defaults::

    JAX_ENABLE_X64=1 timeout -s INT 18000 uv run python -u -m causaldyn_bench.boptest_capped \\
        --url http://127.0.0.1:8000 --out results/boptest_capped      # or: just paper-3-live

``-s INT`` rather than the default ``TERM``: an interrupted episode must reach its ``finally`` and
stop its test, or the orphan holds the service's only worker until the service's own timeout and
every later ``select`` queues behind it. That happened while this design was piloted. Every finished
episode is journalled beside the results, and a rerun resumes from the journal: it recomputes stages
0 and 1 -- the emulator is deterministic -- and refuses to continue if they disagree with it.

**The prediction on record** (Results 56, 66 and 72(d); P3's Theorem 5). Under a per-round cap
the right response is a longer duration, not a gentler shape: at the same total probe energy,
delivering it as fast as the actuator allows -- the greedy fill, a *block* -- costs less regret than
the clipped ``1/sqrt(t)`` *taper*. The theorem is about a model. Nothing below was generated by it.

**Plant and decision.** ``bestest_hydronic_heat_pump`` on the live emulator. Every two hours the
controller sets the heat pump's modulation ``u in [0, 1]`` to hold the zone at 21.5 C and pays
``(T_next - 21.5)^2`` [K^2]. Its model of one round is ``(T_next - T)/dt = drift(T, weather) +
theta u + noise``. The drift is fitted once on a randomised log (stage 0); ``theta`` -- the zone's
heating rate per unit modulation over a round, in K/h -- is the one thing the controller learns, and
it acts on it certainty-equivalently: ``u* = ((21.5 - T)/dt - drift)/theta_hat``, clipped to the
actuator.

Two design choices were made on an unscored pilot and are stated so a reader can dispute them:

* **Not the heat pump's own delivery loop.** Condenser power against modulation is nearly a static
  map on this emulator, so a single probe identifies its slope and no cap can bind. A test in which
  the block and the taper both finish on round one tests nothing.
* **Two-hour rounds.** At half-hour rounds the zone's response to a probe peaks one round *after*
  the round it was applied in -- a plant with memory, outside Result 56's repeated-static-decision
  scope. At two hours the closed-loop response to the previous round's probe is small; stage 1
  measures it and the results print it (``lag1``), so the premise is checked on the scored run
  rather than assumed from the pilot.

**The cap is the actuator's range.** A fair-sign probe ``e = +-sqrt(v)`` around the planned
``u0 = clip(u*, 0, 1)`` has to keep ``u0 + e`` inside ``[0, 1]``, so
``v <= cap_t = min(u0, 1 - u0)^2``: zero at full power and at off, largest mid-range. That is the
heat pump's physical power limit read as a per-round cap on probe energy. It moves with the state,
so it is Result 66's varying cap rather than Result 56's constant one -- and, unlike either, it also
moves with the ESTIMATE, because a wrong ``theta_hat`` moves ``u0``.

**Identification target.** ``theta``, from the injected probe alone: ``y = obs - theta_hat u0``
on ``e``, Robinson's partialling-out moment; the planned action never identifies anything. The
running estimate is ``theta_hat = (I0 theta0 + sum e y/s^2)/(I0 + sum e^2/s^2)``, and the value the
controller ACTS on is floored at ``theta0/4`` -- a known sign, since heating warms the zone. Without
the floor an estimate that crosses zero switches the heat pump off, which closes the cap, which
stops the probe: an absorbing failure the pilot's simulation found and no later data can undo.

**Protocol.**

1. *Stage 0, nuisance.* :func:`log_episode` for 900 rounds from 1 January under a two-hour PRBS,
   then :func:`fit_thermal` with ``adjusted=False`` (the log is randomised).
2. *Stage 1, reference.* 900 rounds from 1 January with a full-cap probe on EVERY round and the
   running estimate in the loop. ``theta_ref`` is the probe-only least-squares effect over all of
   them, ``s`` the residual standard deviation. The block, the taper and the oracle are all judged
   against ``theta_ref``.
3. *Oracle.* Per window, ``theta_hat = theta_ref`` and no probe: the regret baseline, and the caps
   and demands that plan the budget.
4. *Plan -- the predictions, fixed before any arm runs.* ``A = dt^2 theta_ref^2``,
   ``K = dt^2 mean(u*^2)`` over the oracle's rounds (``u*`` counted only strictly inside the
   actuator, where the action depends on the estimate), ``c = 1/s^2``, ``I0 = 1/(0.5 theta_ref)^2``.
   :func:`chc.regret.capped_exploration_policy` on the oracle's mean cap schedule gives the budget
   ``M* = exploration_mass``; the same call at ``budget=M*`` gives ``cost`` and ``taper_cost``, the
   predicted regret of each arm. The map into the library's knobs is gated against its
   ``uncapped_floor`` identity, as :func:`causaldyn_bench.paper_three.plant_constants` does.
5. *Episodes.* Seven windows of 288 rounds (24 days) starting on days 1, 9, ..., 49, after a one-day
   warm-up; 24 seeds per window, so 168 pairs. Seed ``k`` sets the prior ``theta0 = theta_ref
   (1 +- 0.5)``, the sign alternating with ``k``, at precision ``I0``: one prior sd off, so
   ``I0 delta^2 = 1`` (Result 72); and it draws the fair probe signs once, shared by both arms.
   The TAPER runs first, ``v_t = min(kappa/sqrt(t), cap_t)`` at the library's own scale
   ``kappa``, until ``M*`` is spent. The BLOCK then runs on the same signs with the taper's REALISED
   spend as its budget, ``v_t = cap_t`` until it is gone -- the same total, so exactly Theorem 5's
   comparison. A lazy arm per window and prior sign keeps ``theta_hat = theta0`` and never probes.

**Metrics.** Per episode: the loss ``L = sum_t (T_{t+1} - 21.5)^2``, the regret ``R = L - L_oracle``
of its window, the final estimate against ``theta_ref`` with its nominal 95% interval
``+-1.96/sqrt(I0 + S/s^2)``, the realised probe energy ``S``, and BOPTEST's ``tdis_tot`` and
``ener_tot``.

**The gate, fixed before any episode ran.** ``D = R_taper - R_block`` per pair, which the oracle
cancels out of; its mean over the 168 pairs with a 95% percentile bootstrap interval (20 000
resamples, stratified by window, fixed seed). **CONFIRMED** if the interval lies above zero,
**REFUTED** if it lies below, **INCONCLUSIVE** otherwise. The verdict stands only if two validity
checks pass: (V1) the lazy arm's mean regret exceeds the upper end of the block's 95% interval --
otherwise not exploring is competitive and the experiment is not testing exploration at all (R12);
(V2) the block delivered the taper's budget, mean shortfall under 5%. Everything else is secondary
and descriptive: realised against predicted regret per arm, the interval's coverage, the KPIs.

**Power.** 168 pairs is what one sitting on the service's single worker affords. The plan stage
simulates this protocol on a surrogate built from the scored run's own stage 0 and 1 -- the fitted
drift, stage 1's weather and residuals, ``theta_ref`` -- and prints the gap it expects, the spread,
and the pairs it would need for 80% power, all before an arm runs. That figure is a model's; the
surrogate carries the plant's residuals but not its physics.

**Scope, stated before the result.** One emulator, one zone, one season, one target. The deadbeat
controller is deliberately the simplest that makes the decision static; the regret it measures is
relative to the same controller told ``theta_ref``, not to an optimal building controller. A
realised verdict about this plant is not a verdict about Theorem 5, which is proved: it is a
statement about whether the model's premises hold well enough here for its ordering to survive.
"""

from __future__ import annotations

import argparse
import json
import math
from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Literal, Protocol

import numpy as np
from chc.regret import capped_exploration_policy

from causaldyn_bench.boptest import DEFAULT_URL, BOPTestClient, is_available
from causaldyn_bench.boptest_causal import HEAT_PUMP, KELVIN, LOWER_SETP, fit_thermal, log_episode

DAY_S = 86_400.0
Schedule = Literal["block", "taper", "none"]


class Plant(Protocol):
    """The slice of the BOPTEST-Service API an episode uses; :class:`BOPTestClient` is one."""

    def select(self, testcase: str) -> str: ...
    def set_step(self, testid: str, step_s: float) -> Any: ...
    def initialize(self, testid: str, start_time: float, warmup_period: float) -> Any: ...
    def advance(self, testid: str, u: Mapping[str, float]) -> Any: ...
    def forecast(
        self, testid: str, point_names: list[str], horizon: float, interval: float
    ) -> Any: ...
    def kpi(self, testid: str) -> Any: ...
    def stop(self, testid: str) -> Any: ...


@dataclass(frozen=True)
class Design:
    """The pre-registered constants. Changing a default after the scored run is a new experiment."""

    target: float = 21.5
    step_s: float = 7200.0
    rounds: int = 288
    window_days: tuple[int, ...] = (1, 9, 17, 25, 33, 41, 49)
    warmup_days: float = 1.0
    seeds: int = 24
    prior_spread: float = 0.5
    estimate_floor: float = 0.25  # the acted-on estimate never drops below this share of theta0
    nuisance_rounds: int = 900
    reference_rounds: int = 900
    probe_seed: int = 20260927
    bootstrap: int = 20_000
    bootstrap_seed: int = 20260927
    power_seeds: int = 40  # per window, in the plan-time surrogate simulation
    max_shortfall: float = 0.05

    @property
    def dt(self) -> float:
        return self.step_s / 3600.0

    @property
    def rounds_per_day(self) -> int:
        return round(DAY_S / self.step_s)


DESIGN = Design()


@dataclass(frozen=True)
class ZoneModel:
    """Stage 0: the drift the controller subtracts, fitted once on a randomised log.

    ``authority`` is the PRBS fit's own channel at the target. It seeds stage 1's running estimate
    and nothing else -- every arm is judged against the probe-identified ``theta_ref``.
    """

    bias: float
    pole: float
    weather: tuple[float, ...]  # on the standardised [outdoor C, solar kW/m2, comfort bound C]
    weather_mean: tuple[float, ...]
    weather_scale: tuple[float, ...]
    authority: float
    residual_sd: float  # of the PRBS log under the fitted model; weights stage 1's running estimate

    def drift(self, temp: float, covariates: np.ndarray) -> float:
        z = (covariates - np.asarray(self.weather_mean)) / np.asarray(self.weather_scale)
        return self.bias + self.pole * temp + float(np.dot(self.weather, z))


@dataclass(frozen=True)
class Arm:
    """How one episode explores and what it believes when it starts."""

    schedule: Schedule
    budget: float  # total probe energy the episode may spend
    scale: float  # the taper's kappa; the block ignores it
    prior: float  # theta0
    prior_info: float  # I0
    noise_sd: float  # s, the weighting of the running estimate
    floor: float  # the acted-on estimate is max(posterior mean, floor)
    fixed: float | None = None  # a known effect: no learning and no probe (oracle, lazy)


@dataclass(frozen=True)
class Trace:
    """Everything one episode did, round by round. Summaries are pure functions of it."""

    temp: np.ndarray  # zone temperature at the start of each round, C
    covariates: np.ndarray  # (rounds, 3) raw [outdoor C, solar kW/m2, comfort bound C]
    drift: np.ndarray
    planned: np.ndarray  # u0
    demand: np.ndarray  # u* where strictly inside (0, 1), else 0
    cap: np.ndarray
    probe: np.ndarray  # e
    estimate: np.ndarray  # the value acted on in each round
    floored: np.ndarray  # True where the posterior mean sat below the floor and the floor was used
    next_temp: np.ndarray
    posterior: float  # final posterior mean, unfloored
    information: float  # final I0 + S/s^2
    kpi: dict[str, float]


def _probe_energy(schedule: Schedule, t: int, cap: float, left: float, scale: float) -> float:
    """Round ``t`` (1-based) of a schedule: the greedy fill, the clipped taper, or nothing."""
    if schedule == "none" or left <= 0.0:
        return 0.0
    if schedule == "block":
        return min(cap, left)
    return min(scale / math.sqrt(t), cap, left)


def run_episode(
    plant: Plant,
    testid: str,
    model: ZoneModel,
    design: Design,
    arm: Arm,
    *,
    start_day: float,
    signs: np.ndarray,
    rounds: int | None = None,
    warmup_days: float | None = None,
) -> Trace:
    """Drive one episode of ``arm`` on an already-selected test; the plant is reset first."""
    rounds = design.rounds if rounds is None else rounds
    warmup = design.warmup_days if warmup_days is None else warmup_days
    measurements = plant.initialize(testid, start_day * DAY_S, warmup * DAY_S)
    bounds = plant.forecast(testid, [LOWER_SETP], rounds * design.step_s, design.step_s)[LOWER_SETP]
    info, weighted = arm.prior_info, arm.prior_info * arm.prior
    left = arm.budget
    rows: dict[str, list[Any]] = {
        k: []
        for k in (
            "temp",
            "cov",
            "drift",
            "planned",
            "demand",
            "cap",
            "probe",
            "estimate",
            "floored",
            "next",
        )
    }
    for t in range(rounds):
        temp = measurements[HEAT_PUMP.zone_point] - KELVIN
        covariates = np.array(
            [
                measurements[HEAT_PUMP.outdoor_point] - KELVIN,
                measurements[HEAT_PUMP.solar_point] / 1000.0,
                bounds[t] - KELVIN,
            ]
        )
        drift = model.drift(temp, covariates)
        mean = weighted / info
        acted = arm.fixed if arm.fixed is not None else max(mean, arm.floor)
        floored = arm.fixed is None and mean < arm.floor
        wanted = ((design.target - temp) / design.dt - drift) / acted
        planned = min(max(wanted, 0.0), 1.0)
        cap = min(planned, 1.0 - planned) ** 2
        energy = (
            0.0
            if arm.fixed is not None
            else _probe_energy(arm.schedule, t + 1, cap, left, arm.scale)
        )
        left -= energy
        probe = float(signs[t]) * math.sqrt(energy)
        measurements = plant.advance(testid, HEAT_PUMP.overwrite(planned + probe))
        nxt = measurements[HEAT_PUMP.zone_point] - KELVIN
        if arm.fixed is None:
            response = (nxt - temp) / design.dt - drift - acted * planned
            info += probe * probe / arm.noise_sd**2
            weighted += probe * response / arm.noise_sd**2
        for key, value in (
            ("temp", temp),
            ("cov", covariates),
            ("drift", drift),
            ("planned", planned),
            ("demand", wanted if 0.0 < wanted < 1.0 else 0.0),
            ("cap", cap),
            ("probe", probe),
            ("estimate", acted),
            ("floored", floored),
            ("next", nxt),
        ):
            rows[key].append(value)
    kpi = plant.kpi(testid) or {}
    return Trace(
        temp=np.asarray(rows["temp"]),
        covariates=np.asarray(rows["cov"]).reshape(-1, 3),
        drift=np.asarray(rows["drift"]),
        planned=np.asarray(rows["planned"]),
        demand=np.asarray(rows["demand"]),
        cap=np.asarray(rows["cap"]),
        probe=np.asarray(rows["probe"]),
        estimate=np.asarray(rows["estimate"]),
        floored=np.asarray(rows["floored"], dtype=bool),
        next_temp=np.asarray(rows["next"]),
        posterior=float(weighted / info),
        information=float(info),
        kpi={k: float(v) for k, v in kpi.items() if isinstance(v, int | float)},
    )


def loss(trace: Trace, design: Design) -> float:
    return float(np.sum((trace.next_temp - design.target) ** 2))


def fit_zone_model(plant: Plant, design: Design) -> ZoneModel:
    """Stage 0: a randomised two-hour PRBS log and the harness's own linear fit on it."""
    log = log_episode(
        plant,  # ty: ignore[invalid-argument-type]
        HEAT_PUMP,
        policy="prbs",
        seed=0,
        steps=design.nuisance_rounds,
        step_s=design.step_s,
        hold=1,
    )
    fit = fit_thermal(log, adjusted=False)
    zone = np.asarray(log.zone).ravel()
    action = np.asarray(log.action).ravel()
    rate = (np.asarray(log.zone_next).ravel() - zone) / log.dt_hours
    predicted = (
        fit.drift[0]
        + fit.drift[1] * zone
        + np.asarray(log.weather) @ np.asarray(fit.weather_drift)
        + (fit.channel[0] + fit.channel[1] * zone) * action
    )
    return ZoneModel(
        bias=float(fit.drift[0]),
        pole=float(fit.drift[1]),
        weather=tuple(float(c) for c in fit.weather_drift),
        weather_mean=tuple(float(c) for c in log.weather_mean),
        weather_scale=tuple(float(c) for c in log.weather_scale),
        authority=float(fit.authority(design.target)),
        residual_sd=float(np.std(rate - predicted)),
    )


@dataclass(frozen=True)
class Reference:
    """Stage 1: the effect every arm is judged against, and the noise it is identified through."""

    effect: float  # theta_ref, K/h per unit modulation
    noise_sd: float  # s
    energy: float  # total probe energy behind theta_ref
    lag1: float  # response to the PREVIOUS round's probe, jointly fitted; ~0 is the static premise
    first_half: float
    second_half: float
    rounds: int


def reference_effect(trace: Trace, design: Design) -> Reference:
    """Probe-only least squares over a dense-probe trace (the planned action never identifies)."""
    response = (
        (trace.next_temp - trace.temp) / design.dt - trace.drift - (trace.estimate * trace.planned)
    )
    e = trace.probe
    effect = float(np.dot(e, response) / np.dot(e, e))
    residual = response - effect * e
    lagged = np.column_stack([e, np.concatenate([[0.0], e[:-1]])])
    joint, *_ = np.linalg.lstsq(lagged, response, rcond=None)
    half = e.size // 2

    def part(sl: slice) -> float:
        return float(np.dot(e[sl], response[sl]) / np.dot(e[sl], e[sl]))

    return Reference(
        effect=effect,
        noise_sd=float(np.std(residual)),
        energy=float(np.dot(e, e)),
        lag1=float(joint[1]),
        first_half=part(slice(0, half)),
        second_half=part(slice(half, None)),
        rounds=int(e.size),
    )


def residuals(trace: Trace, effect: float, design: Design) -> np.ndarray:
    """What the controller's round model leaves unexplained at the true effect: the surrogate's
    noise."""
    applied = trace.planned + trace.probe
    return (trace.next_temp - trace.temp) / design.dt - trace.drift - effect * applied


@dataclass(frozen=True)
class Plan:
    """The objective's constants on this plant and the library's predictions, before any arm."""

    curvature: float  # A = dt^2 theta_ref^2
    numerator: float  # K = dt^2 mean(u*^2); the noise enters through c, never through K
    info_rate: float  # c = 1/s^2
    prior_info: float  # I0 = 1/(spread theta_ref)^2
    mass: float  # M*, the budget both arms get
    block_rounds: int
    block_cost: float  # predicted regret of the block at M*
    taper_cost: float  # predicted regret of the taper at M*
    scale: float  # kappa, the taper's own scale
    mean_cap: float
    floor_residual: float


def plan_budget(reference: Reference, caps: np.ndarray, demand: np.ndarray, design: Design) -> Plan:
    """Map the plant into Result 56's objective and ask the library for ``M*`` and both costs.

    The library is parametrised by a scalar plant (``b``, ``rr``, ``xt``, ``sigma``, ``eta``,
    ``i0``). ``b = 0``, ``rr = A``, ``xt = sqrt(K A)``, ``sigma = s``, ``eta = 1`` reproduce
    curvature ``A``, numerator ``K`` and information rate ``1/s^2`` exactly; the policy's
    ``uncapped_floor`` is then checked against ``2 sqrt(A K/c) sqrt(T) - A I0/c`` and the plan
    refuses to exist if the two disagree.
    """
    horizon = caps.shape[-1]
    curvature = design.dt**2 * reference.effect**2
    numerator = design.dt**2 * float(np.mean(demand**2))
    info_rate = 1.0 / reference.noise_sd**2
    prior_info = 1.0 / (design.prior_spread * reference.effect) ** 2
    schedule = [float(c) for c in (caps.mean(axis=0) if caps.ndim == 2 else caps)]
    knobs = {
        "b": 0.0,
        "rr": curvature,
        "xt": math.sqrt(numerator * curvature),
        "sigma": reference.noise_sd,
        "eta": 1.0,
        "i0": prior_info,
    }
    free = capped_exploration_policy(horizon=horizon, cap=schedule, **knobs)
    floor = 2.0 * math.sqrt(curvature * numerator / info_rate) * math.sqrt(horizon) - (
        curvature * prior_info / info_rate
    )
    residual = abs(floor - free.uncapped_floor)
    if residual > 1e-9 * max(1.0, abs(floor)):
        raise RuntimeError(
            "the knobs no longer reproduce the plant's constants inside the library: "
            f"uncapped floor off by {residual:.3e}"
        )
    if free.exploration_mass <= 0.0:
        raise RuntimeError(
            "the library plans no exploration on this plant, so there is nothing to compare: "
            f"prior information {prior_info:.3g} already outweighs the horizon"
        )
    budgeted = capped_exploration_policy(
        horizon=horizon, cap=schedule, budget=free.exploration_mass, **knobs
    )
    return Plan(
        curvature=curvature,
        numerator=numerator,
        info_rate=info_rate,
        prior_info=prior_info,
        mass=free.exploration_mass,
        block_rounds=free.block_rounds,
        block_cost=budgeted.cost,
        taper_cost=budgeted.taper_cost,
        scale=reference.noise_sd * math.sqrt(numerator / (2.0 * curvature)),
        mean_cap=float(np.mean(schedule)),
        floor_residual=float(residual),
    )


def prior_for(seed: int, reference: Reference, design: Design) -> tuple[float, float, int]:
    """Seed ``k``: one prior sd off ``theta_ref``, the sign alternating -- ``I0 delta^2 = 1``."""
    sign = 1 if seed % 2 == 0 else -1
    delta = design.prior_spread * reference.effect
    return reference.effect + sign * delta, 1.0 / delta**2, sign


def probe_signs(window: int, seed: int, design: Design) -> np.ndarray:
    rng = np.random.default_rng([design.probe_seed, window, seed])
    return rng.choice(np.array([-1.0, 1.0]), size=design.rounds)


def arm_for(
    schedule: Schedule, budget: float, seed: int, reference: Reference, plan: Plan, design: Design
) -> Arm:
    prior, info, _ = prior_for(seed, reference, design)
    return Arm(
        schedule=schedule,
        budget=budget,
        scale=plan.scale,
        prior=prior,
        prior_info=info,
        noise_sd=reference.noise_sd,
        floor=design.estimate_floor * prior,
    )


def summarise(
    trace: Trace, design: Design, reference: Reference, baseline: float
) -> dict[str, float]:
    """One episode as the numbers the gate and the tables read."""
    energy = trace.probe**2
    spent = float(energy.sum())
    prefix = np.cumsum(energy)
    explored = np.flatnonzero(energy > 0.0)

    def reached(share: float) -> int:
        if spent <= 0.0:
            return 0
        return int(np.searchsorted(prefix, share * spent * (1.0 - 1e-12))) + 1

    half_width = 1.96 / math.sqrt(trace.information)
    error = trace.posterior - reference.effect
    value = loss(trace, design)
    return {
        "loss": value,
        "regret": value - baseline,
        "spent": spent,
        "explored": int(explored.size),
        "last_explored": int(explored[-1]) + 1 if explored.size else 0,
        "half_spent_round": reached(0.5),
        "estimate": trace.posterior,
        "error": error,
        "z": error * math.sqrt(trace.information),
        "covered": float(abs(error) <= half_width),
        "half_width": half_width,
        "floored": int(np.sum(trace.floored)),
        "saturated": int(np.sum(trace.cap <= 0.0)),
        "tdis": trace.kpi.get("tdis_tot", float("nan")),
        "ener": trace.kpi.get("ener_tot", float("nan")),
    }


class SurrogatePlant:
    """A BOPTEST-shaped model plant, for the two jobs that must not touch the live service.

    The plan-time power figure and the offline tests both need something that answers the calls an
    episode makes. A round here is the controller's own model -- ``drift + effect u`` -- plus a
    residual read from ``noise`` at a seeded offset, with the weather and the comfort bound read off
    a recorded trace. It carries the real plant's weather and misfit and none of its physics beyond
    them, so a result that holds only here is a statement about the model.
    """

    def __init__(
        self,
        *,
        model: ZoneModel,
        effect: float,
        covariates: np.ndarray,
        temps: np.ndarray,
        noise: np.ndarray,
        step_s: float,
        offset: int = 0,
    ) -> None:
        self.model, self.effect = model, effect
        self.covariates, self.temps, self.noise = covariates, temps, noise
        self.step_s, self.offset = step_s, offset
        self._round, self._temp = 0, float(temps[0])

    def _measurements(self) -> dict[str, float]:
        outdoor, solar, _ = self.covariates[min(self._round, self.covariates.shape[0] - 1)]
        return {
            HEAT_PUMP.zone_point: self._temp + KELVIN,
            HEAT_PUMP.outdoor_point: float(outdoor) + KELVIN,
            HEAT_PUMP.solar_point: float(solar) * 1000.0,
        }

    def select(self, testcase: str) -> str:
        return "surrogate"

    def set_step(self, testid: str, step_s: float) -> None:
        self.step_s = step_s

    def initialize(self, testid: str, start_time: float, warmup_period: float) -> dict[str, float]:
        self._round = round(start_time / self.step_s)
        if not 0 <= self._round < self.covariates.shape[0]:
            raise ValueError(
                f"start {start_time} s is outside the recorded {self.covariates.shape[0]} rounds"
            )
        self._temp = float(self.temps[self._round])
        return self._measurements()

    def advance(self, testid: str, u: Mapping[str, float]) -> dict[str, float]:
        action = float(np.clip(u.get(HEAT_PUMP.action_point, 0.0), 0.0, 1.0))
        k = min(self._round, self.covariates.shape[0] - 1)
        rate = (
            self.model.drift(self._temp, self.covariates[k])
            + self.effect * action
            + float(self.noise[(k + self.offset) % self.noise.size])
        )
        self._temp += self.step_s / 3600.0 * rate
        self._round += 1
        return self._measurements()

    def forecast(
        self, testid: str, point_names: list[str], horizon: float, interval: float
    ) -> dict[str, list[float]]:
        rows = np.arange(self._round, self._round + round(horizon / interval) + 1)
        rows = np.minimum(rows, self.covariates.shape[0] - 1)
        return {LOWER_SETP: [float(self.covariates[k, 2]) + KELVIN for k in rows]}

    def kpi(self, testid: str) -> dict[str, float]:
        return {}

    def stop(self, testid: str) -> None:
        return None


def _normal_cdf(x: float) -> float:
    return 0.5 * (1.0 + math.erf(x / math.sqrt(2.0)))


def simulated_power(
    model: ZoneModel,
    trace: Trace,
    reference: Reference,
    plan: Plan,
    design: Design,
) -> dict[str, float]:
    """This protocol on the surrogate, before any arm touches the plant: the gap it expects.

    Each simulated pair draws a fresh residual offset and fresh signs, then runs the taper and the
    block on them exactly as the live pairs do. The pairs it would need for 80% power at a two-sided
    5% level is ``(2.8 sd/mean)^2``; the power at the design's own size is the normal approximation.
    """
    noise = residuals(trace, reference.effect, design)
    rng = np.random.default_rng([design.probe_seed, 1])
    gaps = []
    for window, day in enumerate(design.window_days):
        if day * design.rounds_per_day + design.rounds > trace.temp.size:
            raise ValueError(f"window {window} runs past stage 1's record; lengthen stage 1")
        for seed in range(design.power_seeds):
            plant = SurrogatePlant(
                model=model,
                effect=reference.effect,
                covariates=trace.covariates,
                temps=trace.temp,
                noise=noise,
                step_s=design.step_s,
                offset=int(rng.integers(noise.size)),
            )
            signs = rng.choice(np.array([-1.0, 1.0]), size=design.rounds)
            taper = run_episode(
                plant,
                "surrogate",
                model,
                design,
                arm_for("taper", plan.mass, seed, reference, plan, design),
                start_day=day,
                signs=signs,
            )
            spent = float(np.sum(taper.probe**2))
            block = run_episode(
                plant,
                "surrogate",
                model,
                design,
                arm_for("block", spent, seed, reference, plan, design),
                start_day=day,
                signs=signs,
            )
            gaps.append(loss(taper, design) - loss(block, design))
    gap = np.asarray(gaps)
    mean, sd = float(gap.mean()), float(gap.std(ddof=1))
    pairs = len(design.window_days) * design.seeds
    return {
        "pairs_simulated": int(gap.size),
        "mean_gap": mean,
        "sd_gap": sd,
        "pairs_for_80": (2.8 * sd / mean) ** 2 if mean > 0.0 else float("inf"),
        "power_at_design": _normal_cdf(math.sqrt(pairs) * mean / sd - 1.96) if sd > 0 else 0.0,
    }


def _stratified_interval(
    values: np.ndarray, strata: np.ndarray, rng: np.random.Generator, resamples: int
) -> tuple[float, float, float]:
    """Mean and 95% percentile interval, resampling within each stratum (the windows are fixed)."""
    totals = np.zeros(resamples)
    for stratum in np.unique(strata):
        members = values[strata == stratum]
        picks = rng.integers(members.size, size=(resamples, members.size))
        totals += members[picks].sum(axis=1)
    means = totals / values.size
    low, high = np.quantile(means, [0.025, 0.975])
    return float(values.mean()), float(low), float(high)


def verdict(
    pairs: Sequence[Mapping[str, Any]], lazy: Sequence[Mapping[str, Any]], design: Design
) -> dict[str, Any]:
    """The pre-registered gate, applied to whatever the episodes produced."""
    windows = np.array([p["window"] for p in pairs])
    gap = np.array([p["taper"]["regret"] - p["block"]["regret"] for p in pairs])
    block = np.array([p["block"]["regret"] for p in pairs])
    rng = np.random.default_rng(design.bootstrap_seed)
    gap_mean, gap_lo, gap_hi = _stratified_interval(gap, windows, rng, design.bootstrap)
    _, _, block_hi = _stratified_interval(block, windows, rng, design.bootstrap)
    lazy_mean = float(np.mean([entry["regret"] for entry in lazy]))
    shortfalls = [
        max(0.0, (p["taper"]["spent"] - p["block"]["spent"]) / p["taper"]["spent"])
        for p in pairs
        if p["taper"]["spent"] > 0.0
    ]
    shortfall = float(np.mean(shortfalls)) if shortfalls else 0.0
    decision = "CONFIRMED" if gap_lo > 0.0 else "REFUTED" if gap_hi < 0.0 else "INCONCLUSIVE"
    exploring_matters = lazy_mean > block_hi
    budgets_match = shortfall < design.max_shortfall
    return {
        "pairs": int(gap.size),
        "gap_mean": gap_mean,
        "gap_low": gap_lo,
        "gap_high": gap_hi,
        "taper_wins": int(np.sum(gap < 0.0)),
        "decision": decision,
        "lazy_mean_regret": lazy_mean,
        "block_regret_high": block_hi,
        "v1_exploring_matters": bool(exploring_matters),
        "mean_shortfall": shortfall,
        "v2_budgets_match": bool(budgets_match),
        "stands": bool(exploring_matters and budgets_match),
    }


def _read_journal(path: Path | None) -> list[dict[str, Any]]:
    if path is None or not path.exists():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def _append(path: Path | None, record: Mapping[str, Any]) -> None:
    if path is None:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a") as handle:
        handle.write(json.dumps(record) + "\n")


def _selected(plant: Plant, design: Design) -> str:
    testid = plant.select(HEAT_PUMP.testcase)
    plant.set_step(testid, design.step_s)
    return testid


def run_experiment(
    plant: Plant,
    design: Design = DESIGN,
    *,
    journal: Path | None = None,
    say: Any = print,
) -> dict[str, Any]:
    """Stages 0-1, the oracle, the plan and its power, then every pair -- resumable from a journal.

    The journal holds one line per finished lazy episode or pair. Stages 0 and 1, the oracle and the
    plan are recomputed on a resume -- the emulator is deterministic, so they must come back
    identical, and the run refuses to continue if the recomputed plan disagrees with the journal's.
    """
    done = _read_journal(journal)
    model = fit_zone_model(plant, design)
    say(
        f"stage 0: drift ({model.bias:.4f}, {model.pole:.5f}), weather {model.weather}, "
        f"authority {model.authority:.4f}, residual sd {model.residual_sd:.4f}"
    )

    testid = _selected(plant, design)
    try:
        start = Arm(
            schedule="block",
            budget=math.inf,
            scale=0.0,
            prior=model.authority,
            prior_info=1.0 / (design.prior_spread * model.authority) ** 2,
            noise_sd=model.residual_sd,
            floor=design.estimate_floor * model.authority,
        )
        signs = np.random.default_rng([design.probe_seed, 0]).choice(
            np.array([-1.0, 1.0]), size=design.reference_rounds
        )
        dense = run_episode(
            plant,
            testid,
            model,
            design,
            start,
            start_day=0.0,
            signs=signs,
            rounds=design.reference_rounds,
            warmup_days=0.0,
        )
    finally:
        plant.stop(testid)
    reference = reference_effect(dense, design)
    say(
        f"stage 1: theta_ref {reference.effect:.4f} K/h, s {reference.noise_sd:.4f}, energy "
        f"{reference.energy:.3f}, lag1 {reference.lag1:.4f}, halves {reference.first_half:.4f} / "
        f"{reference.second_half:.4f}"
    )

    oracle_arm = Arm(
        schedule="none",
        budget=0.0,
        scale=0.0,
        prior=reference.effect,
        prior_info=1.0,
        noise_sd=reference.noise_sd,
        floor=0.0,
        fixed=reference.effect,
    )
    ones = np.ones(design.rounds)
    oracles: list[Trace] = []
    for day in design.window_days:
        testid = _selected(plant, design)
        try:
            oracles.append(
                run_episode(plant, testid, model, design, oracle_arm, start_day=day, signs=ones)
            )
        finally:
            plant.stop(testid)
    baselines = [loss(trace, design) for trace in oracles]
    plan = plan_budget(
        reference,
        np.stack([trace.cap for trace in oracles]),
        np.stack([trace.demand for trace in oracles]),
        design,
    )
    power = simulated_power(model, dense, reference, plan, design)
    say(
        f"plan: M* {plan.mass:.4f} over {plan.block_rounds} capped rounds, kappa {plan.scale:.4f}; "
        f"predicted regret block {plan.block_cost:.4f}, taper {plan.taper_cost:.4f}; surrogate gap "
        f"{power['mean_gap']:.4f} +- {power['sd_gap']:.4f}, pairs for 80% "
        f"{power['pairs_for_80']:.0f}, power at design {power['power_at_design']:.3f}"
    )

    planned = {"effect": reference.effect, "mass": plan.mass}
    recorded = [entry for entry in done if entry.get("kind") == "plan"]
    if recorded:
        for key, value in planned.items():
            if not math.isclose(float(recorded[0][key]), value, rel_tol=1e-9):
                raise RuntimeError(
                    f"the recomputed {key} {value!r} disagrees with the journal's "
                    f"{recorded[0][key]!r}; the stages are not reproducing -- start a fresh journal"
                )
    else:
        _append(journal, {"kind": "plan", **planned})
    lazy = [entry for entry in done if entry.get("kind") == "lazy"]
    pairs = [entry for entry in done if entry.get("kind") == "pair"]
    have_lazy = {(entry["window"], entry["sign"]) for entry in lazy}
    have_pair = {(entry["window"], entry["seed"]) for entry in pairs}

    for window, day in enumerate(design.window_days):
        testid = _selected(plant, design)
        try:
            for seed in (0, 1):
                prior, info, sign = prior_for(seed, reference, design)
                if (window, sign) in have_lazy:
                    continue
                arm = Arm("none", 0.0, 0.0, prior, info, reference.noise_sd, 0.0, fixed=prior)
                trace = run_episode(plant, testid, model, design, arm, start_day=day, signs=ones)
                entry = {
                    "kind": "lazy",
                    "window": window,
                    "sign": sign,
                    **summarise(trace, design, reference, baselines[window]),
                }
                lazy.append(entry)
                _append(journal, entry)
            for seed in range(design.seeds):
                if (window, seed) in have_pair:
                    continue
                signs = probe_signs(window, seed, design)
                taper = run_episode(
                    plant,
                    testid,
                    model,
                    design,
                    arm_for("taper", plan.mass, seed, reference, plan, design),
                    start_day=day,
                    signs=signs,
                )
                taper_row = summarise(taper, design, reference, baselines[window])
                block = run_episode(
                    plant,
                    testid,
                    model,
                    design,
                    arm_for("block", taper_row["spent"], seed, reference, plan, design),
                    start_day=day,
                    signs=signs,
                )
                block_row = summarise(block, design, reference, baselines[window])
                entry = {
                    "kind": "pair",
                    "window": window,
                    "seed": seed,
                    "sign": prior_for(seed, reference, design)[2],
                    "taper": taper_row,
                    "block": block_row,
                }
                pairs.append(entry)
                _append(journal, entry)
                say(
                    f"window {window} seed {seed}: regret taper {taper_row['regret']:.4f} block "
                    f"{block_row['regret']:.4f} spent {taper_row['spent']:.4f}/"
                    f"{block_row['spent']:.4f}"
                )
        finally:
            plant.stop(testid)

    pairs.sort(key=lambda p: (p["window"], p["seed"]))
    lazy.sort(key=lambda p: (p["window"], -p["sign"]))
    oracle_rows = [
        {
            "window": window,
            "day": day,
            "loss": baselines[window],
            "mean_cap": float(trace.cap.mean()),
            "saturated": float(np.mean(trace.cap <= 0.0)),
            "tdis": trace.kpi.get("tdis_tot", float("nan")),
            "ener": trace.kpi.get("ener_tot", float("nan")),
        }
        for window, (day, trace) in enumerate(zip(design.window_days, oracles, strict=True))
    ]
    return {
        "design": asdict(design),
        "testcase": HEAT_PUMP.testcase,
        "precision": _precision(),
        "model": asdict(model),
        "reference": asdict(reference),
        "plan": asdict(plan),
        "power": power,
        "oracle": oracle_rows,
        "lazy": lazy,
        "pairs": pairs,
        "verdict": verdict(pairs, lazy, design),
    }


def _precision() -> str:
    import jax

    return "float64" if jax.config.read("jax_enable_x64") else "float32"


def _arm_table(pairs: Sequence[Mapping[str, Any]], arm: str) -> dict[str, float]:
    rows = [p[arm] for p in pairs]

    def mean(key: str) -> float:
        return float(np.mean([r[key] for r in rows]))

    return {
        "regret": mean("regret"),
        "spent": mean("spent"),
        "explored": mean("explored"),
        "half_spent_round": float(np.median([r["half_spent_round"] for r in rows])),
        "last_explored": float(np.median([r["last_explored"] for r in rows])),
        "error_rms": float(np.sqrt(np.mean([r["error"] ** 2 for r in rows]))),
        "coverage": mean("covered"),
        "z_variance": float(np.var([r["z"] for r in rows])),
        "floored": mean("floored"),
        "tdis": mean("tdis"),
        "ener": mean("ener"),
    }


def markdown(results: Mapping[str, Any]) -> str:
    """The results file, every number in it read off ``results``."""
    design, model, ref = results["design"], results["model"], results["reference"]
    plan, power, gate = results["plan"], results["power"], results["verdict"]
    arms = {arm: _arm_table(results["pairs"], arm) for arm in ("taper", "block")}
    lazy_regret = float(np.mean([entry["regret"] for entry in results["lazy"]]))
    lines = [
        "# P3.3 -- the capped block against the taper on the live BOPTEST heat pump",
        "",
        "Produced by `causaldyn_bench.boptest_capped` at its pre-registered defaults; the",
        "pre-registration is that module's docstring, committed before this run.",
        "",
        f"- test case `{results['testcase']}`, rounds of {design['step_s'] / 3600.0:g} h, target "
        f"{design['target']} C, {design['rounds']} rounds per episode",
        f"- precision: **{results['precision']}** (`JAX_ENABLE_X64`)",
        f"- windows start on days {', '.join(str(d) for d in design['window_days'])}; "
        f"{design['seeds']} seeds each; {gate['pairs']} pairs",
        "",
        "## Stages 0 and 1",
        "",
        f"- drift `({model['bias']:.4f}, {model['pole']:.5f})`, weather "
        f"`({', '.join(f'{w:.4f}' for w in model['weather'])})`, PRBS authority at the target "
        f"`{model['authority']:.4f}`, PRBS residual sd `{model['residual_sd']:.4f}` K/h",
        f"- `theta_ref = {ref['effect']:.4f}` K/h per unit modulation from probe energy "
        f"`{ref['energy']:.3f}` over {ref['rounds']} rounds; residual sd "
        f"`s = {ref['noise_sd']:.4f}` K/h",
        f"- halves `{ref['first_half']:.4f}` / `{ref['second_half']:.4f}`; response to the "
        f"previous round's probe `lag1 = {ref['lag1']:.4f}`",
        "",
        "## Plan (printed before any arm ran)",
        "",
        f"- `A = {plan['curvature']:.4f}`, `K = {plan['numerator']:.4f}`, "
        f"`c = {plan['info_rate']:.3f}`, `I0 = {plan['prior_info']:.3f}`, mean oracle cap "
        f"`{plan['mean_cap']:.4f}`; floor-identity residual `{plan['floor_residual']:.1e}`",
        f"- budget `M* = {plan['mass']:.4f}`, delivered by the capped block in "
        f"{plan['block_rounds']} rounds of the mean schedule; taper scale `kappa = "
        f"{plan['scale']:.4f}`",
        f"- predicted regret: block `{plan['block_cost']:.4f}`, taper `{plan['taper_cost']:.4f}` "
        f"K^2 per episode",
        f"- surrogate simulation ({power['pairs_simulated']} pairs): gap `{power['mean_gap']:.4f}` "
        f"+- `{power['sd_gap']:.4f}` (sd); pairs for 80% power `{power['pairs_for_80']:.0f}`; "
        f"power at the design's {gate['pairs']} pairs `{power['power_at_design']:.3f}`",
        "",
        "## The gate",
        "",
        f"`D = R_taper - R_block`: mean **{gate['gap_mean']:.4f}** K^2, 95% interval "
        f"[{gate['gap_low']:.4f}, {gate['gap_high']:.4f}] (stratified bootstrap, "
        f"{design['bootstrap']} resamples); the taper won {gate['taper_wins']} of "
        f"{gate['pairs']} pairs.",
        "",
        f"- decision: **{gate['decision']}**",
        f"- V1 (exploring matters): lazy mean regret `{gate['lazy_mean_regret']:.4f}` against the "
        f"block's upper bound `{gate['block_regret_high']:.4f}` -> "
        f"{'pass' if gate['v1_exploring_matters'] else 'FAIL'}",
        f"- V2 (same budget): mean shortfall `{gate['mean_shortfall']:.4f}` -> "
        f"{'pass' if gate['v2_budgets_match'] else 'FAIL'}",
        f"- the verdict {'STANDS' if gate['stands'] else 'DOES NOT STAND'}",
        "",
        "## Arms (means over pairs; rounds are medians)",
        "",
        "| arm | regret K^2 | predicted | spent | rounds probed | half spent by | last probe | "
        "error rms | coverage | var z | floored | tdis K h | ener kWh/m2 |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for arm, predicted in (("block", plan["block_cost"]), ("taper", plan["taper_cost"])):
        row = arms[arm]
        lines.append(
            f"| {arm} | {row['regret']:.4f} | {predicted:.4f} | {row['spent']:.4f} | "
            f"{row['explored']:.1f} | {row['half_spent_round']:.0f} | {row['last_explored']:.0f} | "
            f"{row['error_rms']:.4f} | {row['coverage']:.3f} | {row['z_variance']:.3f} | "
            f"{row['floored']:.1f} | {row['tdis']:.3f} | {row['ener']:.3f} |"
        )
    lines += [
        f"| lazy | {lazy_regret:.4f} | -- | 0 | 0 | -- | -- | -- | -- | -- | -- | "
        f"{float(np.mean([e['tdis'] for e in results['lazy']])):.3f} | "
        f"{float(np.mean([e['ener'] for e in results['lazy']])):.3f} |",
        "",
        "## Per window",
        "",
        "| window | day | oracle loss | mean cap | saturated | mean D | taper wins |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in results["oracle"]:
        mine = [p for p in results["pairs"] if p["window"] == row["window"]]
        gaps = [p["taper"]["regret"] - p["block"]["regret"] for p in mine]
        lines.append(
            f"| {row['window']} | {row['day']} | {row['loss']:.4f} | {row['mean_cap']:.4f} | "
            f"{row['saturated']:.3f} | {float(np.mean(gaps)):.4f} | "
            f"{sum(g < 0.0 for g in gaps)}/{len(gaps)} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--url", default=DEFAULT_URL)
    parser.add_argument("--out", type=Path, default=Path("results/boptest_capped"))
    args = parser.parse_args()
    if _precision() != "float64":
        raise SystemExit(
            "JAX_ENABLE_X64=1 is required: the harness's fits moved 10x in float32 once, and the "
            "precision is recorded next to every number"
        )
    if not is_available(args.url):
        raise RuntimeError(f"no BOPTEST-Service at {args.url}; bring it up and pass --url")
    client = BOPTestClient(args.url, timeout=600.0)
    results = run_experiment(client, Design(), journal=args.out / "journal.jsonl")
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "results.json").write_text(json.dumps(results, indent=2))
    text = markdown(results)
    (args.out / "results.md").write_text(text)
    print(text)
    print(f"written to {args.out}/results.md and {args.out}/results.json")


if __name__ == "__main__":
    main()
